"""One application's PostgreSQL connection; production never falls back to SQLite."""
from __future__ import annotations

import os
import re
import sqlite3

import psycopg2
from psycopg2.extras import DictCursor

SCHEMA = "archive"
ID_TABLES = {"users", "password_resets", "excel_files", "excel_sheets", "excel_cells", "archive_documents"}
LITERALS = re.compile(r"('(?:''|[^'])*'|--[^\n]*(?:\n|$))")


def translate(statement):
    query = statement.strip().rstrip(";")
    query = re.sub(r"CREATE VIRTUAL TABLE (?:IF NOT EXISTS )?archive_documents_fts\s+USING fts5\([^;]+\)",
                   "CREATE TABLE IF NOT EXISTS archive_documents_fts (document_id TEXT, content TEXT)", query, flags=re.I)
    query = query.replace("datetime('now','localtime')", "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS')")
    parts = LITERALS.split(query)
    for index in range(0, len(parts), 2):
        part = re.sub(r"\bINTEGER\s+PRIMARY KEY\s+AUTOINCREMENT\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", parts[index], flags=re.I)
        part = re.sub(r"\bINTEGER\b", "BIGINT", part, flags=re.I)
        part = re.sub(r"\bREAL\b", "DOUBLE PRECISION", part, flags=re.I)
        parts[index] = re.sub(r"\bLIKE\b", "ILIKE", part, flags=re.I)
    query = "".join(parts)
    if re.match(r"INSERT\s+OR\s+IGNORE\b", query, re.I):
        query = re.sub(r"INSERT\s+OR\s+IGNORE", "INSERT", query, count=1, flags=re.I) + " ON CONFLICT DO NOTHING"
    inserted = re.match(r"INSERT\s+INTO\s+(\w+)", query, re.I)
    returns_id = bool(inserted and inserted[1] in ID_TABLES and not re.search(r"\bRETURNING\b", query, re.I))
    if returns_id:
        query += " RETURNING id"
    parts = LITERALS.split(query)
    parts = [re.sub(r"(?<!:):([a-z_][a-z0-9_]*)", r"%(\1)s", part.replace("%", "%%").replace("?", "%s"))
             if index % 2 == 0 else part.replace("%", "%%") for index, part in enumerate(parts)]
    return "".join(parts), returns_id


class Cursor:
    def __init__(self, raw, lastrowid=None):
        self.raw, self.lastrowid, self.rowcount = raw, lastrowid, raw.rowcount

    def fetchone(self):
        return self.raw.fetchone()

    def fetchall(self):
        return self.raw.fetchall()

    def __iter__(self):
        return iter(self.raw)


class Connection:
    is_postgres = True
    row_factory = None

    def __init__(self):
        self.raw = psycopg2.connect(os.environ["DATABASE_URL"], connect_timeout=5,
                                   options=f"-c search_path={SCHEMA} -c statement_timeout=15000 -c lock_timeout=3000")
        if self.raw.info.dbname != "website_business":
            self.raw.close()
            raise RuntimeError("应用只能连接平台的 website_business 数据库")

    def execute(self, statement, parameters=()):
        index = re.match(r"\s*CREATE INDEX IF NOT EXISTS ([a-z_][a-z0-9_]*)\b", statement, flags=re.I)
        if index:
            cursor = self.raw.cursor(cursor_factory=DictCursor)
            cursor.execute("SELECT to_regclass(%s)", (SCHEMA + "." + index[1],))
            if cursor.fetchone()[0] is not None:
                return Cursor(cursor)
            cursor.close()
        query, returns_id = translate(statement)
        cursor = self.raw.cursor(cursor_factory=DictCursor)
        try:
            cursor.execute(query, parameters)
        except psycopg2.IntegrityError:
            raise sqlite3.IntegrityError("duplicate or invalid application record") from None
        row = cursor.fetchone() if returns_id else None
        return Cursor(cursor, row[0] if row else None)

    def executescript(self, script):
        for statement in script.split(";"):
            if statement.strip():
                self.execute(statement)

    def commit(self):
        self.raw.commit()

    def close(self):
        self.raw.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        try:
            self.raw.rollback() if exc_type else self.raw.commit()
        finally:
            self.close()


def connect_database(path, schema, timeout=5):
    if schema != SCHEMA:
        raise RuntimeError("应用不能访问其他数据区域")
    return Connection()
